# Exercise 5: NumPy Fundamentals
This exercise demonstrates how to import and use NumPy for data analytics related purposes

In [2]:
import numpy as np

## Array Basics

In [16]:
# step a
fruits = ["apple", "banana", "cherry", "date"]

In [17]:
# step b
arr_1 = np.array(fruits)

In [18]:
# step c
arr_1.dtype  # returns '<U6'; U is unicode string data type, 6 means longest string element in array is 6 characters

dtype('<U6')

In [19]:
# step d
arr_2 = np.array([(10, 11, 12), (13, 14, 15)])
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [20]:
# step e
print(arr_2.T)  # transposes arr_2

[[10 13]
 [11 14]
 [12 15]]


In [21]:
print(arr_2)  # no change made after transposing

[[10 11 12]
 [13 14 15]]


In [22]:
# step f
arr_3 = np.array([(1, 3, 5), (2, 4, 6)])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [23]:
# step g
arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]])
print(arr_4)

[5 4]


In [30]:
# step h
arr_5 = np.array([[(1, 1), (1, 1)], [(1, 1), (1, 1)]])

# or
# arr_5 = np.ones((2, 2, 2), dtype=int)  # 2 x 2 x 2; 3D array with ones
print(arr_5)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
