# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

## Looping Through Arrays

In [2]:
arrA = np.array([(11, 12, 13), (14, 15, 16)])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [4]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [5]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


Looping through x affects the entire array and doubles each element.
Looping through y affects each individual element in each array, one by one.

In [6]:
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


Instead of printing each element, it doubles and prints the entire array. Beginning with the first array, it saves the doubled version and prints it. Each iteration overrides the previous, and since the original is not changed, it continously prints the array of which it belongs to (x).

## Joining and Stacking Arrays

In [7]:
joined_array_1 = np.concatenate((arrA, arrA))
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [9]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [10]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [12]:
# prints a ValueError: all input arrays must have the same shape (they have different array sizes)
# stacked_array_2 = np.stack((joined_array_1, joined_array_2))

In [13]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [15]:
# prints a ValueError: the dimensions except for the concatenation axis must be equal to each other, but it doesn't. In each array's rows, the first has 4 while the second has 2. All dimensions with the exception of the one its being concatenated on must be matching.
# another_2 = np.concatenate((joined_array_1, arrA), axis=1)