# Exercise 1.A NumPy: Manipulating Arrays

In [26]:
import numpy as np

## Looping Through Arrays

In [27]:
arrA = np.array([(11, 12, 13), (14, 15, 16)])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [28]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [29]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


Looping through x affects the entire array and doubles each element.
Looping through y affects each individual element in each array, one by one.

In [30]:
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


Instead of printing each element, it doubles and prints the entire array. Beginning with the first array, it saves the doubled version and prints it. Each iteration overrides the previous, and since the original is not changed, it continously prints the array of which it belongs to (x).

## Joining and Stacking Arrays

In [31]:
joined_array_1 = np.concatenate((arrA, arrA))
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [32]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [33]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [34]:
# prints a ValueError: all input arrays must have the same shape (they have different array sizes)
# stacked_array_2 = np.stack((joined_array_1, joined_array_2))

In [35]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [36]:
# prints a ValueError: the dimensions except for the concatenation axis must be equal to each other, but it doesn't. In each array's rows, the first has 4 while the second has 2. All dimensions with the exception of the one its being concatenated on must be matching.
# another_2 = np.concatenate((joined_array_1, arrA), axis=1)

In [37]:
# more array manipulation

hor_stack = np.hstack((arrA, arrA))  # horizontal stack; appends arrays horizontally, puts them besides each other and combines columns, same rows, together
print(hor_stack)

ver_stack = np.vstack((arrA, arrA))  # vertical stack; appends arrays vertically, stacks them vertically and parsed each row
print(ver_stack)

dep_stack = np.dstack((arrA, arrA))  # depth stack; stacks arrays along the third axis, for layering 2D images, like axis=2
print(dep_stack)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [38]:
splitsky = np.split(joined_array_1, 2)
print(splitsky)  # splits the joined array, made up on arr1 and arr1, into two arrays (arr1 and arr1), and lists them as two separate arrays (2x3)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [40]:
# spliterino = np.split(joined_array_1, 3)  # could not perform the function as the split function splits from rows, not columns. 4 % 3 == 1, not 0; does not fully and evenly split
# print(spliterino)

## Searching and Replacing Array Values

In [41]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [45]:
arrB = np.array([(7,6), (13, 5), (7, 3)])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)  # sorts each row individually by axis=1

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [51]:
print(arrB)

z = arrB < 7

arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [52]:
w = arrB >= 7

arrD = arrB[w]
print(arrD)

[ 7 13  7]
