# Exercise 1.B NumPy Random

In [3]:
import numpy as np

## Generating Random Numbers

In [4]:
r_1 = np.random.randint(1, 21, size=2)
print(r_1)

[2 1]


In [5]:
r_2 = np.random.randint(1, 21, size=(1, 2))
print(r_2)

[[11  7]]


In [6]:
r_3 = np.random.uniform(0, 1, size=(2, 1))
print(r_3)

[[0.36682277]
 [0.41991389]]


In [7]:
r_4 = np.random.randint(20, 101, size=(4, 5))
print(r_4)

[[47 95 94 90 34]
 [98 81 32 89 47]
 [28 39 70 70 44]
 [96 39 23 42 84]]


In [8]:
r_5 = np.random.uniform(0, 1, size=(4, 5))
print(r_5)

[[0.80665418 0.74734733 0.29598423 0.40434406 0.96368212]
 [0.97728801 0.87951216 0.22965507 0.51617439 0.78216021]
 [0.38192033 0.32113565 0.61169146 0.84292066 0.46334946]
 [0.61206245 0.710649   0.33312409 0.64737498 0.91040711]]


## Generating Random Choices from an Array

In [9]:
students = np.array([
    "Onur", "Jessica", "Julissa", "Jimmy", "Maritza",
    "Tracy", "Paul", "Kiki", "Will", "Shaq",
    "Fuat", "El" # , "Rae", "Angel", "Ceyhun",
    #"Shay", "Paola", "Eyerusalem", "Cagla", "David"
])

In [10]:
call_on = np.random.choice(students)
print(call_on)

Kiki


In [11]:
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)  # not quite an effective way to assign breakout rooms because some rooms have the same participants

[['Paul' 'Will' 'Paul' 'Maritza']
 ['Maritza' 'Maritza' 'El' 'Tracy']
 ['Tracy' 'Paul' 'Shaq' 'Tracy']]


In [12]:
p_values = [0.10, 0.30, 0.08, 0.00, 0.10, 0.05, 0.08, 0.05, 0.05, 0.05, 0.05, 0.09]  # based on how likely I am to collaborate with them on a future project

call_on_weighted = np.random.choice(students, size=5, replace = False, p = p_values)  # added replace condition to pick without replacement

print(call_on_weighted)

['Maritza' 'Julissa' 'Jessica' 'El' 'Tracy']


## Generating a Normal Distribution

In [13]:
bell_curve = np.random.normal(loc = 10, scale = 5, size = (4, 5))
print(bell_curve)

[[ 2.9976321   8.09262555 10.44647744 11.70856617  6.23846743]
 [ 6.50502355 11.09825031 15.2204521  11.13156086 12.19015682]
 [15.20982666  9.78587681  9.2061256  13.70224616 17.93526519]
 [14.90261863  1.88259687 14.17135099 15.66204901 13.13930803]]
