# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In [2]:
r_1 = np.random.randint(1, 21, size=2)
r_2 = np.random.randint(1, 21, size=(1, 2))
r_3 = np.random.uniform(0, 1, size=(2, 1))
r_4 = np.random.randint(20, 101, size=(4, 5))
r_5 = np.random.uniform(0, 1, size=(4, 5))

## Permutations

In [3]:
print(r_4)

[[ 92  81  95  78  55]
 [ 90  44  25  39  39]
 [ 71  24  58 100  87]
 [ 89  41  85  97  41]]


In [4]:
np.random.shuffle(r_4)
print(r_4)

[[ 89  41  85  97  41]
 [ 92  81  95  78  55]
 [ 90  44  25  39  39]
 [ 71  24  58 100  87]]


Each row was kept the same; however, the order in which they appeared changed.

In [5]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)
print(r_4)

[[ 71  24  58 100  87]
 [ 90  44  25  39  39]
 [ 89  41  85  97  41]
 [ 92  81  95  78  55]]
[[ 89  41  85  97  41]
 [ 92  81  95  78  55]
 [ 90  44  25  39  39]
 [ 71  24  58 100  87]]


'np.random.shuffle()' randomizes and modifies the original array permanently
'np.random.permutation()' randomizes the original array too, but unlike .shuffle(), it does not modify the original array permanently.

## Mathematical Operations

In [6]:
print(r_1)
print(r_1.shape)

print(r_2)
print(r_2.shape)

print(np.add(r_1, r_2))
print(np.add(r_1, r_2).shape)

[17 18]
(2,)
[[12 20]]
(1, 2)
[[29 38]]
(1, 2)


In [7]:
print(r_1)
print(r_1.shape)

print(r_3)
print(r_3.shape)

print(np.add(r_1, r_3))
print(np.add(r_1, r_3).shape)

[17 18]
(2,)
[[0.30838188]
 [0.53817697]]
(2, 1)
[[17.30838188 18.30838188]
 [17.53817697 18.53817697]]
(2, 2)


In [8]:
print(r_2)
print(r_2.shape)

print(r_4)
print(r_4.shape)

# print(np.add(r_2, r_4))
# print(np.add(r_2, r_4).shape)  # could not be broadcasted together with different shapes; last dimensions must be equal or one of them must be 1

[[12 20]]
(1, 2)
[[ 89  41  85  97  41]
 [ 92  81  95  78  55]
 [ 90  44  25  39  39]
 [ 71  24  58 100  87]]
(4, 5)


In [9]:
# print(np.add(r_1, r_4))
# ValueError: operands could not be broadcast together with shapes (2,) (4,5)

# print(np.add(r_2, r_4))
# ValueError: operands could not be broadcast together with shapes (1,2) (4,5)

# print(np.add(r_3, r_4))
# ValueError: operands could not be broadcast together with shapes (2,1) (4,5)

# same error as before, different shapes, last dimensions are not equal

In [10]:
print(np.add(np.array([1]), r_4))  # adds 1 to all elements in each array

[[ 90  42  86  98  42]
 [ 93  82  96  79  56]
 [ 91  45  26  40  40]
 [ 72  25  59 101  88]]


In [11]:
print(np.add(np.array([[1]]), r_4))  # adds 1 to all elements in each array, dimensions are 1, so no conflict happens

[[ 90  42  86  98  42]
 [ 93  82  96  79  56]
 [ 91  45  26  40  40]
 [ 72  25  59 101  88]]


In [12]:
print(np.add(np.array([1,1,1,1,1]), r_4))  # columns match up, adds 1 to all rows for each corresponding column

[[ 90  42  86  98  42]
 [ 93  82  96  79  56]
 [ 91  45  26  40  40]
 [ 72  25  59 101  88]]


In [14]:
#print(np.add(np.array([[1], [1]]), r_4))  # columns don't match up, 2x1 vs 4x5

NumPy reads the shape of arrays from right to left. If they're the same or one is equal to 1, NumPy extends the shape, or broadcasts, the smaller array to match the larger one. The add function depends on how the arrays line up after broadcasting, and they are arithmetically added based on their corresponding position. The shape of the final array is determined by the largest array of the two.

## Rounding

In [15]:
print(r_3)

[[0.30838188]
 [0.53817697]]


In [16]:
print(np.trunc(r_3))  # cuts the decimal portion off

[[0.]
 [0.]]


In [17]:
print(np.fix(r_3))  # rounds towards zero, works for both positive and negative numbers

[[0.]
 [0.]]


In [18]:
print(np.floor(r_3))  # rounds down to the nearest integer

[[0.]
 [0.]]


In [19]:
print(np.ceil(r_3))  # rounds up to the nearest integer

[[1.]
 [1.]]


In [20]:
print(np.round(r_3, 2))  # rounds to 2 decimal places

[[0.31]
 [0.54]]


## Cumulative Operations