# Exercise 1.C Performing operations on arrays

In [44]:
import numpy as np

## Sample Arrays

In [45]:
r_1 = np.random.randint(1, 21, size=2)
r_2 = np.random.randint(1, 21, size=(1, 2))
r_3 = np.random.uniform(0, 1, size=(2, 1))
r_4 = np.random.randint(20, 101, size=(4, 5))
r_5 = np.random.uniform(0, 1, size=(4, 5))

## Permutations

In [46]:
print(r_4)

[[80 41 45 77 61]
 [50 28 39 95 92]
 [99 48 78 72 65]
 [50 34 35 46 75]]


In [47]:
np.random.shuffle(r_4)
print(r_4)

[[99 48 78 72 65]
 [50 34 35 46 75]
 [80 41 45 77 61]
 [50 28 39 95 92]]


Each row was kept the same; however, the order in which they appeared changed.

In [48]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)
print(r_4)

[[80 41 45 77 61]
 [50 28 39 95 92]
 [99 48 78 72 65]
 [50 34 35 46 75]]
[[99 48 78 72 65]
 [50 34 35 46 75]
 [80 41 45 77 61]
 [50 28 39 95 92]]


'np.random.shuffle()' randomizes and modifies the original array permanently
'np.random.permutation()' randomizes the original array too, but unlike .shuffle(), it does not modify the original array permanently.

## Mathematical Operations

In [49]:
print(r_1)
print(r_1.shape)

print(r_2)
print(r_2.shape)

print(np.add(r_1, r_2))
print(np.add(r_1, r_2).shape)

[ 4 10]
(2,)
[[ 3 16]]
(1, 2)
[[ 7 26]]
(1, 2)


In [50]:
print(r_1)
print(r_1.shape)

print(r_3)
print(r_3.shape)

print(np.add(r_1, r_3))
print(np.add(r_1, r_3).shape)

[ 4 10]
(2,)
[[0.51763935]
 [0.56370091]]
(2, 1)
[[ 4.51763935 10.51763935]
 [ 4.56370091 10.56370091]]
(2, 2)


In [51]:
print(r_2)
print(r_2.shape)

print(r_4)
print(r_4.shape)

# print(np.add(r_2, r_4))
# print(np.add(r_2, r_4).shape)  # could not be broadcasted together with different shapes; last dimensions must be equal or one of them must be 1

[[ 3 16]]
(1, 2)
[[99 48 78 72 65]
 [50 34 35 46 75]
 [80 41 45 77 61]
 [50 28 39 95 92]]
(4, 5)


In [52]:
# print(np.add(r_1, r_4))
# ValueError: operands could not be broadcast together with shapes (2,) (4,5)

# print(np.add(r_2, r_4))
# ValueError: operands could not be broadcast together with shapes (1,2) (4,5)

# print(np.add(r_3, r_4))
# ValueError: operands could not be broadcast together with shapes (2,1) (4,5)

# same error as before, different shapes, last dimensions are not equal

In [53]:
print(np.add(np.array([1]), r_4))  # adds 1 to all elements in each array

[[100  49  79  73  66]
 [ 51  35  36  47  76]
 [ 81  42  46  78  62]
 [ 51  29  40  96  93]]


In [54]:
print(np.add(np.array([[1]]), r_4))  # adds 1 to all elements in each array, dimensions are 1, so no conflict happens

[[100  49  79  73  66]
 [ 51  35  36  47  76]
 [ 81  42  46  78  62]
 [ 51  29  40  96  93]]


In [55]:
print(np.add(np.array([1,1,1,1,1]), r_4))  # columns match up, adds 1 to all rows for each corresponding column

[[100  49  79  73  66]
 [ 51  35  36  47  76]
 [ 81  42  46  78  62]
 [ 51  29  40  96  93]]


In [56]:
#print(np.add(np.array([[1], [1]]), r_4))  # columns don't match up, 2x1 vs 4x5

NumPy reads the shape of arrays from right to left. If they're the same or one is equal to 1, NumPy extends the shape, or broadcasts, the smaller array to match the larger one. The add function depends on how the arrays line up after broadcasting, and they are arithmetically added based on their corresponding position. The shape of the final array is determined by the largest array of the two.

## Rounding

In [57]:
print(r_3)

[[0.51763935]
 [0.56370091]]


In [58]:
print(np.trunc(r_3))  # cuts the decimal portion off

[[0.]
 [0.]]


In [59]:
print(np.fix(r_3))  # rounds towards zero, works for both positive and negative numbers

[[0.]
 [0.]]


In [60]:
print(np.floor(r_3))  # rounds down to the nearest integer

[[0.]
 [0.]]


In [61]:
print(np.ceil(r_3))  # rounds up to the nearest integer

[[1.]
 [1.]]


In [62]:
print(np.round(r_3, 2))  # rounds to 2 decimal places

[[0.52]
 [0.56]]


## Cumulative Operations

In [63]:
print(r_4)

[[99 48 78 72 65]
 [50 34 35 46 75]
 [80 41 45 77 61]
 [50 28 39 95 92]]


In [64]:
print(np.sum(r_4))

1210


In [65]:
print(np.sum(r_4, axis=0))

[279 151 197 290 293]


In [66]:
print(np.sum(r_4, axis=1))

[362 240 304 304]


In [67]:
print(np.cumsum(r_4))

[  99  147  225  297  362  412  446  481  527  602  682  723  768  845
  906  956  984 1023 1118 1210]


In [68]:
print(np.cumsum(r_4, axis=0))

[[ 99  48  78  72  65]
 [149  82 113 118 140]
 [229 123 158 195 201]
 [279 151 197 290 293]]


## Grocery Problem

In [69]:
vegetables = ["Carrot", "Broccoli", "Spinach", "Lettuce", "Cucumber", "Onion", "Potato", "Bell pepper", "Corn", "Green beans", "Cauliflower"]
fruits = ["Tomato", "Apple", "Banana", "Orange", "Grapes", "Strawberry", "Blueberry", "Watermelon", "Pineapple", "Mango", "Peach", "Pear", "Kiwi"]
snacks = ["Chips", "Pretzels", "Popcorn", "Crackers", "Granola bars", "Trail mix", "Cookies", "Nuts", "Yogurt", "Cheese sticks", "Fruit snacks", "Chocolate"]
beverages = ["Water", "Coffee", "Tea", "Orange juice", "Apple juice", "Soda", "Lemonade", "Milk", "Sports drinks", "Smoothies", "Hot chocolate", "Sparkling water"]

bag1 = np.array(list(np.random.choice(vegetables, 2, replace = False)) + list(np.random.choice(fruits, 3, replace = False)) + list(np.random.choice(snacks, 4, replace = False)) + list(np.random.choice(beverages, 0, replace = False)))
bag2 = np.array(list(np.random.choice(vegetables, 4, replace = False)) + list(np.random.choice(fruits, 0, replace = False)) + list(np.random.choice(snacks, 1, replace = False)) + list(np.random.choice(beverages, 2, replace = False)))
print(bag1)
print(bag2)

['Potato' 'Carrot' 'Blueberry' 'Pineapple' 'Watermelon' 'Cheese sticks'
 'Fruit snacks' 'Granola bars' 'Pretzels']
['Onion' 'Potato' 'Green beans' 'Corn' 'Yogurt' 'Milk' 'Water']


In [70]:
print(f"The first bag contains {bag1.size} items, and the second bag contains {bag2.size} items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [71]:
all_items = np.concatenate((bag1, bag2))

veg_count = np.isin(all_items, vegetables).sum()
fruit_count = np.isin(all_items, fruits).sum()
snack_count = np.isin(all_items, snacks).sum()
bev_count = np.isin(all_items, beverages).sum()

print(f"There are {veg_count} vegetables, {fruit_count} fruits, {snack_count} boxes of snacks, and {bev_count} beverages in the two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [72]:
ali_doors = np.array([5, 4, 6, 4, 2])


In [73]:
ben_doors = np.array([0, 5, 5, 3, 4])

In [74]:
carla_doors = np.array([3, 6, 0, 6, 3])

In [78]:
all_knocks = np.add(np.add(ali_doors, ben_doors), carla_doors)
print(f"Weekly Summary (M-F): {all_knocks}; total knocks: {all_knocks.sum()}")

Weekly Summary (M-F): [ 8 15 11 13  9]; total knocks: 56


In [79]:
cumsum_vote = np.cumsum(all_knocks) * 0.5
print(cumsum_vote)

[ 4.  11.5 17.  23.5 28. ]
